package types

import "encoding/binary"

const (
	// Sizes below are the kernel ringbuf payload sizes, i.e. sizeof(struct ...)
	// from internal/c/types.h compiled for the BPF/LP64 target. The kernel
	// reserves sizeof(struct) via bpf_ringbuf_reserve, which for structs whose
	// last field is 32-bit but that also contain a __u64 includes trailing
	// padding to the struct's 8-byte alignment. The fast path must therefore
	// gate on sizeof, not on the sum of field widths, or it silently falls back
	// to the slow binary.Read path on the hot events (open/read/write/ret/...).
	//
	// Compact sizes are the unpadded field sums produced by binary.Write (used
	// by generated Bytes methods and tests). Legacy sizes describe payloads
	// from a pre-schema-change IOR_BPF_OBJECT. The widened path-like structs
	// retain their old field prefix, so the fast decoders can accept both and
	// supply AT_FDCWD for the dirfd fields absent from legacy records.
	openEventSize                = 320
	openEventCompactSize         = 316
	openEventLegacyKernelSize    = 304
	openEventLegacyCompactSize   = 300
	openNameFixupEventSize       = 268
	execEventSize                = 304
	nullEventSize                = 24
	fdEventSize                  = 32
	fdEventCompactSize           = 28
	fdEventLegacyKernelSize      = 48
	fdEventLegacyCompactSize     = 44
	fdSizeEventSize              = 48
	fdSizeEventCompactSize       = 44
	retEventSize                 = 40
	retEventSizeV1               = 36
	nameEventSize                = 560
	nameEventLegacySize          = 536
	pathEventSize                = 312
	pathEventCompactSize         = 312
	pathEventV3KernelSize        = 304
	pathEventV3CompactSize       = 300
	pathEventLegacySize          = 280
	fdPathEventSize              = 304
	fdPathEventCompactSize       = 300
	fcntlEventSize               = 40
	dup3EventSize                = 32
	openByHandleAtEventSize      = 32
	openByHandleAtEventSizeV1    = 28
	socketEventSize              = 40
	socketEventSizeV1            = 36
	socketpairEventSize          = 56
	socketpairEventSizeV1        = 52
	acceptEventSize              = 48
	acceptEventCompactSize       = 44
	acceptEventLegacyKernelSize  = 40
	acceptEventLegacyCompactSize = 36
	pipeEventSize                = 48
	pipeEventSizeV1              = 44
	eventfdEventSize             = 48
	eventfdNameEventSize         = 312
	// V3 is the former padded layout with fd. V2 predates fd, while V1 is its
	// compact binary.Write form.
	eventfdEventSizeV3         = 48
	eventfdEventSizeV2         = 40
	eventfdEventSizeV1         = 36
	epollCtlEventSize          = 40
	twoFdEventSize             = 48
	twoFdCompactSize           = 44
	twoFdNamesEventSize        = 568
	twoFdNamesCompactSize      = 564
	twoFdLegacySize            = 40
	pollEventSize              = 48
	pollEventCompactSize       = 44
	pollEventLegacyKernelSize  = 40
	pollEventLegacyCompactSize = 36
	memEventSize               = 56
	mmapEventSize              = 64
	mmapEventSizeV1            = 60
	sleepEventSize             = 32
	keyctlEventSize            = 40
	ptraceEventSize            = 48
	perfOpenEventSize          = 56
	// process_exec_event is not a syscall event; it is the control record
	// emitted by sched:sched_process_exec. 4+4+8+4+4+16 = 40 bytes with no
	// trailing padding, so kernel and binary.Write payloads share one size.
	processExecEventSize = 40
	// process_exit_event is the sibling control record emitted by
	// sched:sched_process_exit. 4+4+8+4+4 = 24 bytes, no trailing padding.
	processExitEventSize = 24
)

const legacyPathDirfd = int32(-100) // AT_FDCWD

// NewOpenEventFast decodes one open ring-buffer payload in a
// single pass. Only the released pre-i4 layout and the current schema are
// accepted; intermediate development layouts are ambiguous and fail closed.
func NewOpenEventFast(raw []byte) *OpenEvent {
	if len(raw) < openEventLegacyCompactSize {
		return nil
	}
	legacy := len(raw) == openEventLegacyCompactSize || len(raw) == openEventLegacyKernelSize
	current := len(raw) == openEventCompactSize || len(raw) == openEventSize
	if !legacy && !current {
		return nil
	}
	o := poolOfOpenEvents.Get().(*OpenEvent)
	o.EventType = EventType(binary.LittleEndian.Uint32(raw[0:4]))
	o.TraceId = TraceId(binary.LittleEndian.Uint32(raw[4:8]))
	o.Time = binary.LittleEndian.Uint64(raw[8:16])
	o.Pid = binary.LittleEndian.Uint32(raw[16:20])
	o.Tid = binary.LittleEndian.Uint32(raw[20:24])
	o.Flags = int32(binary.LittleEndian.Uint32(raw[24:28]))
	copy(o.Filename[:], raw[28:284])
	copy(o.Comm[:], raw[284:300])
	o.Dirfd = legacyPathDirfd
	o.SchemaVersion = 0
	o.FilenameStatus = PATH_READ_OK
	o.SchemaReserved = 0
	if current {
		o.Dirfd = int32(binary.LittleEndian.Uint32(raw[300:304]))
		o.SchemaVersion = binary.LittleEndian.Uint32(raw[304:308])
		o.FilenameStatus = binary.LittleEndian.Uint32(raw[308:312])
		o.SchemaReserved = binary.LittleEndian.Uint32(raw[312:316])
		if o.SchemaVersion != OPEN_EVENT_SCHEMA_VERSION {
			o.Recycle()
			return nil
		}
	}
	return o
}

// NewOpenNameFixupEventFast decodes the compact control record that carries a
// filename recovered at sys_exit. It also accepts the former open_event layout
// so a pre-change IOR_BPF_OBJECT remains compatible. Unknown layouts return
// nil rather than risk interpreting an unrelated offset as the tid or name.
func NewOpenNameFixupEventFast(raw []byte) *OpenNameFixupEvent {
	var tidOffset, filenameOffset int
	switch len(raw) {
	case openNameFixupEventSize:
		tidOffset = 8
		filenameOffset = 12
	case openEventLegacyKernelSize, openEventLegacyCompactSize:
		// OPEN_NAME_FIXUP_EVENT originally reused struct open_event. Accept
		// both its kernel sizeof and historical binary.Write layouts.
		tidOffset = 20
		filenameOffset = 28
	default:
		return nil
	}
	o := poolOfOpenNameFixupEvents.Get().(*OpenNameFixupEvent)
	o.EventType = EventType(binary.LittleEndian.Uint32(raw[0:4]))
	o.TraceId = TraceId(binary.LittleEndian.Uint32(raw[4:8]))
	o.Tid = binary.LittleEndian.Uint32(raw[tidOffset : tidOffset+4])
	copy(o.Filename[:], raw[filenameOffset:filenameOffset+MAX_FILENAME_LENGTH])
	return o
}

// NewExecEventFast decodes one exec ring-buffer payload in a
// single pass, falling back to the slow binary.Read decoder when the
// payload size does not match the size constant above. Returns nil for a
// short payload.
func NewExecEventFast(raw []byte) *ExecEvent {
	if len(raw) < execEventSize {
		return nil
	}
	if len(raw) != execEventSize {
		return NewExecEvent(raw)
	}
	e := poolOfExecEvents.Get().(*ExecEvent)
	e.EventType = EventType(binary.LittleEndian.Uint32(raw[0:4]))
	e.TraceId = TraceId(binary.LittleEndian.Uint32(raw[4:8]))
	e.Time = binary.LittleEndian.Uint64(raw[8:16])
	e.Pid = binary.LittleEndian.Uint32(raw[16:20])
	e.Tid = binary.LittleEndian.Uint32(raw[20:24])
	e.Dirfd = int32(binary.LittleEndian.Uint32(raw[24:28]))
	e.Flags = int32(binary.LittleEndian.Uint32(raw[28:32]))
	copy(e.Filename[:], raw[32:288])
	copy(e.Comm[:], raw[288:304])
	return e
}

// NewNullEventFast decodes one null ring-buffer payload in a
// single pass, falling back to the slow binary.Read decoder when the
// payload size does not match the size constant(s) above. Returns nil
// for a short payload.
func NewNullEventFast(raw []byte) *NullEvent {
	if len(raw) < nullEventSize {
		return nil
	}
	if len(raw) != nullEventSize {
		return NewNullEvent(raw)
	}
	n := poolOfNullEvents.Get().(*NullEvent)
	n.EventType = EventType(binary.LittleEndian.Uint32(raw[0:4]))
	n.TraceId = TraceId(binary.LittleEndian.Uint32(raw[4:8]))
	n.Time = binary.LittleEndian.Uint64(raw[8:16])
	n.Pid = binary.LittleEndian.Uint32(raw[16:20])
	n.Tid = binary.LittleEndian.Uint32(raw[20:24])
	return n
}

// NewFdEventFast decodes one fd ring-buffer payload in a
// single pass, falling back to the slow binary.Read decoder when the
// payload size does not match the size constant(s) above. Returns nil
// for a short payload.
func NewFdEventFast(raw []byte) *FdEvent {
	if len(raw) < fdEventCompactSize {
		return nil
	}
	legacy := len(raw) == fdEventCompactSize || len(raw) == fdEventSize
	current := len(raw) == fdEventLegacyCompactSize || len(raw) == fdEventLegacyKernelSize
	if !legacy && !current {
		return nil
	}
	f := poolOfFdEvents.Get().(*FdEvent)
	f.EventType = EventType(binary.LittleEndian.Uint32(raw[0:4]))
	f.TraceId = TraceId(binary.LittleEndian.Uint32(raw[4:8]))
	f.Time = binary.LittleEndian.Uint64(raw[8:16])
	f.Pid = binary.LittleEndian.Uint32(raw[16:20])
	f.Tid = binary.LittleEndian.Uint32(raw[20:24])
	f.Fd = int32(binary.LittleEndian.Uint32(raw[24:28]))
	f.Size = 0
	f.SizeValid = 0
	f.SchemaVersion = 0
	if current {
		sizeOffset := 28
		if len(raw) == fdEventLegacyKernelSize {
			sizeOffset = 32
		}
		f.Size = binary.LittleEndian.Uint64(raw[sizeOffset : sizeOffset+8])
		f.SizeValid = binary.LittleEndian.Uint32(raw[sizeOffset+8 : sizeOffset+12])
		f.SchemaVersion = binary.LittleEndian.Uint32(raw[sizeOffset+12 : sizeOffset+16])
		if f.SchemaVersion != FD_EVENT_SCHEMA_VERSION {
			f.Recycle()
			return nil
		}
	}
	return f
}

// NewFdSizeEventFast decodes the requested-size variant used by fd xattrs.
func NewFdSizeEventFast(raw []byte) *FdSizeEvent {
	if len(raw) != fdSizeEventSize && len(raw) != fdSizeEventCompactSize {
		return nil
	}
	f := poolOfFdSizeEvents.Get().(*FdSizeEvent)
	f.EventType = EventType(binary.LittleEndian.Uint32(raw[0:4]))
	f.TraceId = TraceId(binary.LittleEndian.Uint32(raw[4:8]))
	f.Time = binary.LittleEndian.Uint64(raw[8:16])
	f.Pid = binary.LittleEndian.Uint32(raw[16:20])
	f.Tid = binary.LittleEndian.Uint32(raw[20:24])
	f.Fd = int32(binary.LittleEndian.Uint32(raw[24:28]))
	offset := 28
	if len(raw) == fdSizeEventSize {
		offset = 32
	}
	f.Size = binary.LittleEndian.Uint64(raw[offset : offset+8])
	f.SizeValid = binary.LittleEndian.Uint32(raw[offset+8 : offset+12])
	f.SchemaVersion = binary.LittleEndian.Uint32(raw[offset+12 : offset+16])
	if f.SchemaVersion != FD_SIZE_EVENT_SCHEMA_VERSION {
		f.Recycle()
		return nil
	}
	return f
}

// NewRetEventFast decodes one ret ring-buffer payload in a
// single pass, falling back to the slow binary.Read decoder when the
// payload size does not match the size constant(s) above. Returns nil
// for a short payload.
func NewRetEventFast(raw []byte) *RetEvent {
	if len(raw) < retEventSizeV1 {
		return nil
	}
	if len(raw) != retEventSize && len(raw) != retEventSizeV1 {
		return NewRetEvent(raw)
	}
	r := poolOfRetEvents.Get().(*RetEvent)
	r.EventType = EventType(binary.LittleEndian.Uint32(raw[0:4]))
	r.TraceId = TraceId(binary.LittleEndian.Uint32(raw[4:8]))
	r.Time = binary.LittleEndian.Uint64(raw[8:16])
	r.Ret = int64(binary.LittleEndian.Uint64(raw[16:24]))
	r.Pid = binary.LittleEndian.Uint32(raw[24:28])
	r.Tid = binary.LittleEndian.Uint32(raw[28:32])
	r.RetType = binary.LittleEndian.Uint32(raw[32:36])
	return r
}

// NewNameEventFast decodes one name ring-buffer payload in a
// single pass, falling back to the slow binary.Read decoder when the
// payload size does not match the size constant(s) above. Returns nil
// for a short payload.
func NewNameEventFast(raw []byte) *NameEvent {
	if len(raw) < nameEventLegacySize {
		return nil
	}
	legacy := len(raw) == nameEventLegacySize
	current := len(raw) == nameEventSize
	if !legacy && !current {
		return nil
	}
	n := poolOfNameEvents.Get().(*NameEvent)
	n.EventType = EventType(binary.LittleEndian.Uint32(raw[0:4]))
	n.TraceId = TraceId(binary.LittleEndian.Uint32(raw[4:8]))
	n.Time = binary.LittleEndian.Uint64(raw[8:16])
	n.Pid = binary.LittleEndian.Uint32(raw[16:20])
	n.Tid = binary.LittleEndian.Uint32(raw[20:24])
	copy(n.Oldname[:], raw[24:280])
	copy(n.Newname[:], raw[280:536])
	n.Olddirfd = legacyPathDirfd
	n.Newdirfd = legacyPathDirfd
	n.OldnameStatus = PATH_READ_OK
	n.NewnameStatus = PATH_READ_OK
	if current {
		n.Olddirfd = int32(binary.LittleEndian.Uint32(raw[536:540]))
		n.Newdirfd = int32(binary.LittleEndian.Uint32(raw[540:544]))
		n.OldnameStatus = binary.LittleEndian.Uint32(raw[544:548])
		n.NewnameStatus = binary.LittleEndian.Uint32(raw[548:552])
		n.Flags = binary.LittleEndian.Uint32(raw[552:556])
		n.SchemaVersion = binary.LittleEndian.Uint32(raw[556:560])
		if n.SchemaVersion != NAME_EVENT_SCHEMA_VERSION {
			n.Recycle()
			return nil
		}
	} else {
		n.Flags = 0
		n.SchemaVersion = 0
	}
	return n
}

// NewPathEventFast decodes one path ring-buffer payload in a
// single pass. Only the released pre-i4 layout and the current schema are
// accepted. In particular, the abandoned dirfd-only kernel layout and the
// abandoned status layout both occupied 288 bytes, so accepting either would
// interpret padding as trusted read status.
func NewPathEventFast(raw []byte) *PathEvent {
	if len(raw) < pathEventLegacySize {
		return nil
	}
	legacy := len(raw) == pathEventLegacySize
	v3 := len(raw) == pathEventV3CompactSize || len(raw) == pathEventV3KernelSize
	current := len(raw) == pathEventCompactSize || len(raw) == pathEventSize
	if !legacy && !v3 && !current {
		return nil
	}
	p := poolOfPathEvents.Get().(*PathEvent)
	p.EventType = EventType(binary.LittleEndian.Uint32(raw[0:4]))
	p.TraceId = TraceId(binary.LittleEndian.Uint32(raw[4:8]))
	p.Time = binary.LittleEndian.Uint64(raw[8:16])
	p.Pid = binary.LittleEndian.Uint32(raw[16:20])
	p.Tid = binary.LittleEndian.Uint32(raw[20:24])
	copy(p.Pathname[:], raw[24:280])
	p.Dirfd = legacyPathDirfd
	p.PathnameStatus = PATH_READ_OK
	p.TargetStatus = PATH_TARGET_REQUIRED
	p.Size = 0
	p.SizeValid = 0
	if v3 || current {
		p.Dirfd = int32(binary.LittleEndian.Uint32(raw[280:284]))
		p.PathnameStatus = binary.LittleEndian.Uint32(raw[284:288])
		p.Flags = binary.LittleEndian.Uint32(raw[288:292])
		p.SchemaVersion = binary.LittleEndian.Uint32(raw[292:296])
		p.TargetStatus = binary.LittleEndian.Uint32(raw[296:300])
		wantSchema := uint32(3)
		if current {
			wantSchema = PATH_EVENT_SCHEMA_VERSION
		}
		if p.SchemaVersion != wantSchema {
			p.Recycle()
			return nil
		}
		if current {
			p.SizeValid = binary.LittleEndian.Uint32(raw[300:304])
			p.Size = binary.LittleEndian.Uint64(raw[304:312])
		}
	} else {
		p.Flags = 0
		p.SchemaVersion = 0
	}
	return p
}

// NewFdPathEventFast decodes the notification-group/path payload. Its distinct
// event type leaves legacy inotify fd and fanotify path payloads unambiguous.
func NewFdPathEventFast(raw []byte) *FdPathEvent {
	if len(raw) != fdPathEventSize && len(raw) != fdPathEventCompactSize {
		return nil
	}
	if binary.LittleEndian.Uint32(raw[296:300]) != FD_PATH_EVENT_SCHEMA_VERSION {
		return nil
	}
	p := poolOfFdPathEvents.Get().(*FdPathEvent)
	p.EventType = EventType(binary.LittleEndian.Uint32(raw[0:4]))
	p.TraceId = TraceId(binary.LittleEndian.Uint32(raw[4:8]))
	p.Time = binary.LittleEndian.Uint64(raw[8:16])
	p.Pid = binary.LittleEndian.Uint32(raw[16:20])
	p.Tid = binary.LittleEndian.Uint32(raw[20:24])
	p.Fd = int32(binary.LittleEndian.Uint32(raw[24:28]))
	p.Dirfd = int32(binary.LittleEndian.Uint32(raw[28:32]))
	copy(p.Pathname[:], raw[32:288])
	p.PathnameStatus = binary.LittleEndian.Uint32(raw[288:292])
	p.Flags = binary.LittleEndian.Uint32(raw[292:296])
	p.SchemaVersion = binary.LittleEndian.Uint32(raw[296:300])
	return p
}

// NewFcntlEventFast decodes one fcntl ring-buffer payload in a
// single pass, falling back to the slow binary.Read decoder when the
// payload size does not match the size constant(s) above. Returns nil
// for a short payload.
func NewFcntlEventFast(raw []byte) *FcntlEvent {
	if len(raw) < fcntlEventSize {
		return nil
	}
	if len(raw) != fcntlEventSize {
		return NewFcntlEvent(raw)
	}
	f := poolOfFcntlEvents.Get().(*FcntlEvent)
	f.EventType = EventType(binary.LittleEndian.Uint32(raw[0:4]))
	f.TraceId = TraceId(binary.LittleEndian.Uint32(raw[4:8]))
	f.Time = binary.LittleEndian.Uint64(raw[8:16])
	f.Pid = binary.LittleEndian.Uint32(raw[16:20])
	f.Tid = binary.LittleEndian.Uint32(raw[20:24])
	f.Fd = binary.LittleEndian.Uint32(raw[24:28])
	f.Cmd = binary.LittleEndian.Uint32(raw[28:32])
	f.Arg = binary.LittleEndian.Uint64(raw[32:40])
	return f
}

// NewDup3EventFast decodes one dup3 ring-buffer payload in a
// single pass, falling back to the slow binary.Read decoder when the
// payload size does not match the size constant(s) above. Returns nil
// for a short payload.
func NewDup3EventFast(raw []byte) *Dup3Event {
	if len(raw) < dup3EventSize {
		return nil
	}
	if len(raw) != dup3EventSize {
		return NewDup3Event(raw)
	}
	d := poolOfDup3Events.Get().(*Dup3Event)
	d.EventType = EventType(binary.LittleEndian.Uint32(raw[0:4]))
	d.TraceId = TraceId(binary.LittleEndian.Uint32(raw[4:8]))
	d.Time = binary.LittleEndian.Uint64(raw[8:16])
	d.Pid = binary.LittleEndian.Uint32(raw[16:20])
	d.Tid = binary.LittleEndian.Uint32(raw[20:24])
	d.Fd = int32(binary.LittleEndian.Uint32(raw[24:28]))
	d.Flags = int32(binary.LittleEndian.Uint32(raw[28:32]))
	return d
}

// NewOpenByHandleAtEventFast decodes one open_by_handle_at ring-buffer payload in a
// single pass, falling back to the slow binary.Read decoder when the
// payload size does not match the size constant(s) above. Returns nil
// for a short payload.
func NewOpenByHandleAtEventFast(raw []byte) *OpenByHandleAtEvent {
	if len(raw) < openByHandleAtEventSizeV1 {
		return nil
	}
	if len(raw) != openByHandleAtEventSize && len(raw) != openByHandleAtEventSizeV1 {
		return NewOpenByHandleAtEvent(raw)
	}
	o := poolOfOpenByHandleAtEvents.Get().(*OpenByHandleAtEvent)
	o.EventType = EventType(binary.LittleEndian.Uint32(raw[0:4]))
	o.TraceId = TraceId(binary.LittleEndian.Uint32(raw[4:8]))
	o.Time = binary.LittleEndian.Uint64(raw[8:16])
	o.Pid = binary.LittleEndian.Uint32(raw[16:20])
	o.Tid = binary.LittleEndian.Uint32(raw[20:24])
	o.Flags = int32(binary.LittleEndian.Uint32(raw[24:28]))
	return o
}

// NewSocketEventFast decodes one socket ring-buffer payload in a
// single pass, falling back to the slow binary.Read decoder when the
// payload size does not match the size constant(s) above. Returns nil
// for a short payload.
func NewSocketEventFast(raw []byte) *SocketEvent {
	if len(raw) < socketEventSizeV1 {
		return nil
	}
	if len(raw) != socketEventSize && len(raw) != socketEventSizeV1 {
		return NewSocketEvent(raw)
	}
	s := poolOfSocketEvents.Get().(*SocketEvent)
	s.EventType = EventType(binary.LittleEndian.Uint32(raw[0:4]))
	s.TraceId = TraceId(binary.LittleEndian.Uint32(raw[4:8]))
	s.Time = binary.LittleEndian.Uint64(raw[8:16])
	s.Pid = binary.LittleEndian.Uint32(raw[16:20])
	s.Tid = binary.LittleEndian.Uint32(raw[20:24])
	s.Family = int32(binary.LittleEndian.Uint32(raw[24:28]))
	s.Type = int32(binary.LittleEndian.Uint32(raw[28:32]))
	s.Protocol = int32(binary.LittleEndian.Uint32(raw[32:36]))
	return s
}

// NewSocketpairEventFast decodes one socketpair ring-buffer payload in a
// single pass, falling back to the slow binary.Read decoder when the
// payload size does not match the size constant(s) above. Returns nil
// for a short payload.
func NewSocketpairEventFast(raw []byte) *SocketpairEvent {
	if len(raw) < socketpairEventSizeV1 {
		return nil
	}
	if len(raw) != socketpairEventSize && len(raw) != socketpairEventSizeV1 {
		return NewSocketpairEvent(raw)
	}
	s := poolOfSocketpairEvents.Get().(*SocketpairEvent)
	s.EventType = EventType(binary.LittleEndian.Uint32(raw[0:4]))
	s.TraceId = TraceId(binary.LittleEndian.Uint32(raw[4:8]))
	s.Time = binary.LittleEndian.Uint64(raw[8:16])
	s.Pid = binary.LittleEndian.Uint32(raw[16:20])
	s.Tid = binary.LittleEndian.Uint32(raw[20:24])
	s.Family = int32(binary.LittleEndian.Uint32(raw[24:28]))
	s.Type = int32(binary.LittleEndian.Uint32(raw[28:32]))
	s.Protocol = int32(binary.LittleEndian.Uint32(raw[32:36]))
	s.Sv0 = int32(binary.LittleEndian.Uint32(raw[36:40]))
	s.Sv1 = int32(binary.LittleEndian.Uint32(raw[40:44]))
	retOffset := 44
	if len(raw) == socketpairEventSize {
		retOffset = 48
	}
	s.Ret = int64(binary.LittleEndian.Uint64(raw[retOffset : retOffset+8]))
	return s
}

// NewAcceptEventFast decodes one accept ring-buffer payload in a single pass.
// The legacy layouts ended after Ret; their kernel padding must never be read
// as flags, so they decode with unknown flags. Unknown current layouts fail
// closed instead of guessing at offsets.
func NewAcceptEventFast(raw []byte) *AcceptEvent {
	if len(raw) < acceptEventLegacyCompactSize {
		return nil
	}
	legacy := len(raw) == acceptEventLegacyCompactSize || len(raw) == acceptEventLegacyKernelSize
	current := len(raw) == acceptEventCompactSize || len(raw) == acceptEventSize
	if !legacy && !current {
		return nil
	}
	a := poolOfAcceptEvents.Get().(*AcceptEvent)
	a.EventType = EventType(binary.LittleEndian.Uint32(raw[0:4]))
	a.TraceId = TraceId(binary.LittleEndian.Uint32(raw[4:8]))
	a.Time = binary.LittleEndian.Uint64(raw[8:16])
	a.Pid = binary.LittleEndian.Uint32(raw[16:20])
	a.Tid = binary.LittleEndian.Uint32(raw[20:24])
	a.Fd = int32(binary.LittleEndian.Uint32(raw[24:28]))
	retOffset := 28
	if len(raw) == acceptEventLegacyKernelSize || len(raw) == acceptEventSize {
		retOffset = 32
	}
	a.Ret = int64(binary.LittleEndian.Uint64(raw[retOffset : retOffset+8]))
	a.Flags = -1
	a.SchemaVersion = 0
	if current {
		flagsOffset := retOffset + 8
		a.Flags = int32(binary.LittleEndian.Uint32(raw[flagsOffset : flagsOffset+4]))
		a.SchemaVersion = binary.LittleEndian.Uint32(raw[flagsOffset+4 : flagsOffset+8])
		if a.SchemaVersion != ACCEPT_EVENT_SCHEMA_VERSION {
			a.Recycle()
			return nil
		}
	}
	return a
}

// NewPipeEventFast decodes one pipe ring-buffer payload in a
// single pass, falling back to the slow binary.Read decoder when the
// payload size does not match the size constant(s) above. Returns nil
// for a short payload.
func NewPipeEventFast(raw []byte) *PipeEvent {
	if len(raw) < pipeEventSizeV1 {
		return nil
	}
	if len(raw) != pipeEventSize && len(raw) != pipeEventSizeV1 {
		return NewPipeEvent(raw)
	}
	p := poolOfPipeEvents.Get().(*PipeEvent)
	p.EventType = EventType(binary.LittleEndian.Uint32(raw[0:4]))
	p.TraceId = TraceId(binary.LittleEndian.Uint32(raw[4:8]))
	p.Time = binary.LittleEndian.Uint64(raw[8:16])
	p.Pid = binary.LittleEndian.Uint32(raw[16:20])
	p.Tid = binary.LittleEndian.Uint32(raw[20:24])
	p.Flags = int32(binary.LittleEndian.Uint32(raw[24:28]))
	p.Fd0 = int32(binary.LittleEndian.Uint32(raw[28:32]))
	p.Fd1 = int32(binary.LittleEndian.Uint32(raw[32:36]))
	retOffset := 36
	if len(raw) == pipeEventSize {
		retOffset = 40
	}
	p.Ret = int64(binary.LittleEndian.Uint64(raw[retOffset : retOffset+8]))
	return p
}

// NewEventfdEventFast decodes one eventfd ring-buffer payload in a
// single pass, falling back to the slow binary.Read decoder when the
// payload size does not match the size constant(s) above. Returns nil
// for a short payload.
func NewEventfdEventFast(raw []byte) *EventfdEvent {
	if len(raw) < eventfdEventSizeV1 {
		return nil
	}
	if len(raw) != eventfdNameEventSize && len(raw) != eventfdEventSize && len(raw) != eventfdEventSizeV2 && len(raw) != eventfdEventSizeV1 {
		return NewEventfdEvent(raw)
	}
	e := poolOfEventfdEvents.Get().(*EventfdEvent)
	e.EventType = EventType(binary.LittleEndian.Uint32(raw[0:4]))
	e.TraceId = TraceId(binary.LittleEndian.Uint32(raw[4:8]))
	e.Time = binary.LittleEndian.Uint64(raw[8:16])
	e.Pid = binary.LittleEndian.Uint32(raw[16:20])
	e.Tid = binary.LittleEndian.Uint32(raw[20:24])
	e.Flags = int32(binary.LittleEndian.Uint32(raw[24:28]))
	e.Fd = -1
	e.Filename = [MAX_FILENAME_LENGTH]byte{}
	e.FilenameStatus = PATH_READ_NULL
	e.SchemaVersion = 0
	retOffset := 28
	if len(raw) >= eventfdEventSizeV2 {
		retOffset = 32
	}
	e.Ret = int64(binary.LittleEndian.Uint64(raw[retOffset : retOffset+8]))
	if len(raw) == eventfdEventSize || len(raw) == eventfdNameEventSize {
		e.Fd = int32(binary.LittleEndian.Uint32(raw[40:44]))
	}
	if len(raw) == eventfdNameEventSize {
		copy(e.Filename[:], raw[44:300])
		e.FilenameStatus = binary.LittleEndian.Uint32(raw[300:304])
		e.SchemaVersion = binary.LittleEndian.Uint32(raw[304:308])
		if e.SchemaVersion != EVENTFD_EVENT_SCHEMA_VERSION {
			e.Recycle()
			return nil
		}
	}
	return e
}

// NewEventfdNameEventFast decodes the wide name-bearing eventfd record.
func NewEventfdNameEventFast(raw []byte) *EventfdNameEvent {
	return NewEventfdNameEvent(raw)
}

// NewEpollCtlEventFast decodes one epoll_ctl ring-buffer payload in a
// single pass, falling back to the slow binary.Read decoder when the
// payload size does not match the size constant(s) above. Returns nil
// for a short payload.
func NewEpollCtlEventFast(raw []byte) *EpollCtlEvent {
	if len(raw) < epollCtlEventSize {
		return nil
	}
	if len(raw) != epollCtlEventSize {
		return NewEpollCtlEvent(raw)
	}
	e := poolOfEpollCtlEvents.Get().(*EpollCtlEvent)
	e.EventType = EventType(binary.LittleEndian.Uint32(raw[0:4]))
	e.TraceId = TraceId(binary.LittleEndian.Uint32(raw[4:8]))
	e.Time = binary.LittleEndian.Uint64(raw[8:16])
	e.Pid = binary.LittleEndian.Uint32(raw[16:20])
	e.Tid = binary.LittleEndian.Uint32(raw[20:24])
	e.Epfd = int32(binary.LittleEndian.Uint32(raw[24:28]))
	e.Op = int32(binary.LittleEndian.Uint32(raw[28:32]))
	e.Fd = int32(binary.LittleEndian.Uint32(raw[32:36]))
	e.Events = binary.LittleEndian.Uint32(raw[36:40])
	return e
}

// NewTwoFdEventFast decodes one two-fd ring-buffer payload in a
// single pass, falling back to the slow binary.Read decoder when the
// payload size does not match the size constant(s) above. Returns nil
// for a short payload.
func NewTwoFdEventFast(raw []byte) *TwoFdEvent {
	if len(raw) < twoFdLegacySize {
		return nil
	}
	legacy := len(raw) == twoFdLegacySize
	current := len(raw) == twoFdCompactSize || len(raw) == twoFdEventSize ||
		len(raw) == twoFdNamesCompactSize || len(raw) == twoFdNamesEventSize
	if !legacy && !current {
		return NewTwoFdEvent(raw)
	}
	t := poolOfTwoFdEvents.Get().(*TwoFdEvent)
	t.EventType = EventType(binary.LittleEndian.Uint32(raw[0:4]))
	t.TraceId = TraceId(binary.LittleEndian.Uint32(raw[4:8]))
	t.Time = binary.LittleEndian.Uint64(raw[8:16])
	t.Pid = binary.LittleEndian.Uint32(raw[16:20])
	t.Tid = binary.LittleEndian.Uint32(raw[20:24])
	t.FdA = int32(binary.LittleEndian.Uint32(raw[24:28]))
	t.FdB = int32(binary.LittleEndian.Uint32(raw[28:32]))
	t.Extra = binary.LittleEndian.Uint64(raw[32:40])
	t.Oldname = [MAX_FILENAME_LENGTH]byte{}
	t.Newname = [MAX_FILENAME_LENGTH]byte{}
	t.OldnameStatus = PATH_READ_NULL
	t.NewnameStatus = PATH_READ_NULL
	t.SchemaVersion = 0
	if len(raw) == twoFdNamesCompactSize || len(raw) == twoFdNamesEventSize {
		copy(t.Oldname[:], raw[40:296])
		copy(t.Newname[:], raw[296:552])
		t.OldnameStatus = binary.LittleEndian.Uint32(raw[552:556])
		t.NewnameStatus = binary.LittleEndian.Uint32(raw[556:560])
		t.SchemaVersion = binary.LittleEndian.Uint32(raw[560:564])
		if t.SchemaVersion != TWO_FD_EVENT_SCHEMA_VERSION &&
			t.SchemaVersion != TWO_FD_EVENT_PRE_KCMP_OWNER_SCHEMA_VERSION {
			t.Recycle()
			return nil
		}
	} else if current {
		t.SchemaVersion = binary.LittleEndian.Uint32(raw[40:44])
		if t.SchemaVersion != TWO_FD_EVENT_SCHEMA_VERSION {
			t.Recycle()
			return nil
		}
	}
	return t
}

// NewTwoFdNamesEventFast decodes the wide pathname-bearing two-fd record.
func NewTwoFdNamesEventFast(raw []byte) *TwoFdNamesEvent {
	return NewTwoFdNamesEvent(raw)
}

// NewPollEventFast decodes one poll ring-buffer payload in a
// single pass. The released 36/40-byte legacy layouts and the schema-gated
// 44/48-byte current layouts are accepted; all other sizes fail closed.
func NewPollEventFast(raw []byte) *PollEvent {
	if len(raw) < pollEventLegacyCompactSize {
		return nil
	}
	legacy := len(raw) == pollEventLegacyCompactSize || len(raw) == pollEventLegacyKernelSize
	current := len(raw) == pollEventCompactSize || len(raw) == pollEventSize
	if !legacy && !current {
		return nil
	}
	p := poolOfPollEvents.Get().(*PollEvent)
	p.EventType = EventType(binary.LittleEndian.Uint32(raw[0:4]))
	p.TraceId = TraceId(binary.LittleEndian.Uint32(raw[4:8]))
	p.Time = binary.LittleEndian.Uint64(raw[8:16])
	p.Pid = binary.LittleEndian.Uint32(raw[16:20])
	p.Tid = binary.LittleEndian.Uint32(raw[20:24])
	p.Nfds = int32(binary.LittleEndian.Uint32(raw[24:28]))
	timeoutOffset := 28
	if len(raw) == pollEventLegacyKernelSize || len(raw) == pollEventSize {
		timeoutOffset = 32
	}
	p.TimeoutNs = int64(binary.LittleEndian.Uint64(raw[timeoutOffset : timeoutOffset+8]))
	p.Fd = -1
	p.SchemaVersion = 0
	if current {
		p.Fd = int32(binary.LittleEndian.Uint32(raw[timeoutOffset+8 : timeoutOffset+12]))
		p.SchemaVersion = binary.LittleEndian.Uint32(raw[timeoutOffset+12 : timeoutOffset+16])
		if p.SchemaVersion != POLL_EVENT_SCHEMA_VERSION {
			*p = PollEvent{}
			p.Recycle()
			return nil
		}
	}
	return p
}

// NewMemEventFast decodes one mem ring-buffer payload in a
// single pass, falling back to the slow binary.Read decoder when the
// payload size does not match the size constant(s) above. Returns nil
// for a short payload.
func NewMemEventFast(raw []byte) *MemEvent {
	if len(raw) < memEventSize {
		return nil
	}
	if len(raw) != memEventSize {
		return NewMemEvent(raw)
	}
	m := poolOfMemEvents.Get().(*MemEvent)
	m.EventType = EventType(binary.LittleEndian.Uint32(raw[0:4]))
	m.TraceId = TraceId(binary.LittleEndian.Uint32(raw[4:8]))
	m.Time = binary.LittleEndian.Uint64(raw[8:16])
	m.Pid = binary.LittleEndian.Uint32(raw[16:20])
	m.Tid = binary.LittleEndian.Uint32(raw[20:24])
	m.Addr = binary.LittleEndian.Uint64(raw[24:32])
	m.Length = binary.LittleEndian.Uint64(raw[32:40])
	m.Length2 = binary.LittleEndian.Uint64(raw[40:48])
	m.Flags = binary.LittleEndian.Uint64(raw[48:56])
	return m
}

// NewMmapEventFast decodes one mmap ring-buffer payload in a single pass.
// It accepts both the kernel's aligned sizeof(struct mmap_event) payload and
// the unpadded field-sum layout emitted by MmapEvent.Bytes in tests.
func NewMmapEventFast(raw []byte) *MmapEvent {
	if len(raw) < mmapEventSizeV1 {
		return nil
	}
	if len(raw) != mmapEventSize && len(raw) != mmapEventSizeV1 {
		return NewMmapEvent(raw)
	}
	m := poolOfMmapEvents.Get().(*MmapEvent)
	m.EventType = EventType(binary.LittleEndian.Uint32(raw[0:4]))
	m.TraceId = TraceId(binary.LittleEndian.Uint32(raw[4:8]))
	m.Time = binary.LittleEndian.Uint64(raw[8:16])
	m.Pid = binary.LittleEndian.Uint32(raw[16:20])
	m.Tid = binary.LittleEndian.Uint32(raw[20:24])
	m.Addr = binary.LittleEndian.Uint64(raw[24:32])
	m.Length = binary.LittleEndian.Uint64(raw[32:40])
	m.Prot = binary.LittleEndian.Uint64(raw[40:48])
	m.Flags = binary.LittleEndian.Uint64(raw[48:56])
	m.Fd = int32(binary.LittleEndian.Uint32(raw[56:60]))
	return m
}

// NewSleepEventFast decodes one sleep ring-buffer payload in a
// single pass, falling back to the slow binary.Read decoder when the
// payload size does not match the size constant(s) above. Returns nil
// for a short payload.
func NewSleepEventFast(raw []byte) *SleepEvent {
	if len(raw) < sleepEventSize {
		return nil
	}
	if len(raw) != sleepEventSize {
		return NewSleepEvent(raw)
	}
	s := poolOfSleepEvents.Get().(*SleepEvent)
	s.EventType = EventType(binary.LittleEndian.Uint32(raw[0:4]))
	s.TraceId = TraceId(binary.LittleEndian.Uint32(raw[4:8]))
	s.Time = binary.LittleEndian.Uint64(raw[8:16])
	s.Pid = binary.LittleEndian.Uint32(raw[16:20])
	s.Tid = binary.LittleEndian.Uint32(raw[20:24])
	s.RequestedNs = int64(binary.LittleEndian.Uint64(raw[24:32]))
	return s
}

// NewKeyctlEventFast decodes one keyctl ring-buffer payload in a
// single pass, falling back to the slow binary.Read decoder when the
// payload size does not match the size constant(s) above. Returns nil
// for a short payload.
func NewKeyctlEventFast(raw []byte) *KeyctlEvent {
	if len(raw) < keyctlEventSize {
		return nil
	}
	if len(raw) != keyctlEventSize {
		return NewKeyctlEvent(raw)
	}
	k := poolOfKeyctlEvents.Get().(*KeyctlEvent)
	k.EventType = EventType(binary.LittleEndian.Uint32(raw[0:4]))
	k.TraceId = TraceId(binary.LittleEndian.Uint32(raw[4:8]))
	k.Time = binary.LittleEndian.Uint64(raw[8:16])
	k.Pid = binary.LittleEndian.Uint32(raw[16:20])
	k.Tid = binary.LittleEndian.Uint32(raw[20:24])
	k.Option = int32(binary.LittleEndian.Uint32(raw[24:28]))
	k.KeySerial = int32(binary.LittleEndian.Uint32(raw[28:32]))
	k.Value = binary.LittleEndian.Uint64(raw[32:40])
	return k
}

// NewPtraceEventFast decodes one ptrace ring-buffer payload in a
// single pass, falling back to the slow binary.Read decoder when the
// payload size does not match the size constant(s) above. Returns nil
// for a short payload.
func NewPtraceEventFast(raw []byte) *PtraceEvent {
	if len(raw) < ptraceEventSize {
		return nil
	}
	if len(raw) != ptraceEventSize {
		return NewPtraceEvent(raw)
	}
	p := poolOfPtraceEvents.Get().(*PtraceEvent)
	p.EventType = EventType(binary.LittleEndian.Uint32(raw[0:4]))
	p.TraceId = TraceId(binary.LittleEndian.Uint32(raw[4:8]))
	p.Time = binary.LittleEndian.Uint64(raw[8:16])
	p.Pid = binary.LittleEndian.Uint32(raw[16:20])
	p.Tid = binary.LittleEndian.Uint32(raw[20:24])
	p.Request = int64(binary.LittleEndian.Uint64(raw[24:32]))
	p.TargetPid = int32(binary.LittleEndian.Uint32(raw[32:36]))
	p.Pad = int32(binary.LittleEndian.Uint32(raw[36:40]))
	p.Data = binary.LittleEndian.Uint64(raw[40:48])
	return p
}

// NewPerfOpenEventFast decodes one perf_event_open payload in a single pass,
// falling back to the slow binary.Read decoder on unexpected lengths and
// returning nil for a short payload.
func NewPerfOpenEventFast(raw []byte) *PerfOpenEvent {
	if len(raw) < perfOpenEventSize {
		return nil
	}
	if len(raw) != perfOpenEventSize {
		return NewPerfOpenEvent(raw)
	}
	p := poolOfPerfOpenEvents.Get().(*PerfOpenEvent)
	p.EventType = EventType(binary.LittleEndian.Uint32(raw[0:4]))
	p.TraceId = TraceId(binary.LittleEndian.Uint32(raw[4:8]))
	p.Time = binary.LittleEndian.Uint64(raw[8:16])
	p.Pid = binary.LittleEndian.Uint32(raw[16:20])
	p.Tid = binary.LittleEndian.Uint32(raw[20:24])
	p.AttrType = binary.LittleEndian.Uint32(raw[24:28])
	p.AttrSize = binary.LittleEndian.Uint32(raw[28:32])
	p.Config = binary.LittleEndian.Uint64(raw[32:40])
	p.TargetPid = int32(binary.LittleEndian.Uint32(raw[40:44]))
	p.Cpu = int32(binary.LittleEndian.Uint32(raw[44:48]))
	p.GroupFd = int32(binary.LittleEndian.Uint32(raw[48:52]))
	p.Flags = binary.LittleEndian.Uint32(raw[52:56])
	return p
}

// NewProcessExecEventFast decodes the sched:sched_process_exec control record
// carrying the post-exec task comm.
func NewProcessExecEventFast(raw []byte) *ProcessExecEvent {
	if len(raw) < processExecEventSize {
		return nil
	}
	if len(raw) != processExecEventSize {
		return NewProcessExecEvent(raw)
	}
	p := poolOfProcessExecEvents.Get().(*ProcessExecEvent)
	p.EventType = EventType(binary.LittleEndian.Uint32(raw[0:4]))
	p.TraceId = TraceId(binary.LittleEndian.Uint32(raw[4:8]))
	p.Time = binary.LittleEndian.Uint64(raw[8:16])
	p.Pid = binary.LittleEndian.Uint32(raw[16:20])
	p.Tid = binary.LittleEndian.Uint32(raw[20:24])
	copy(p.Comm[:], raw[24:40])
	return p
}

// NewProcessExitEventFast decodes the sched:sched_process_exit control record
// identifying the tgid whose fd-table entries userspace must evict.
func NewProcessExitEventFast(raw []byte) *ProcessExitEvent {
	if len(raw) < processExitEventSize {
		return nil
	}
	if len(raw) != processExitEventSize {
		return NewProcessExitEvent(raw)
	}
	p := poolOfProcessExitEvents.Get().(*ProcessExitEvent)
	p.EventType = EventType(binary.LittleEndian.Uint32(raw[0:4]))
	p.TraceId = TraceId(binary.LittleEndian.Uint32(raw[4:8]))
	p.Time = binary.LittleEndian.Uint64(raw[8:16])
	p.Pid = binary.LittleEndian.Uint32(raw[16:20])
	p.Tid = binary.LittleEndian.Uint32(raw[20:24])
	return p
}
