// Code generated - don't change manually!
package tracepoints

var List = []string{
	"sys_enter_socket",
	"sys_exit_socket",
	"sys_enter_socketpair",
	"sys_exit_socketpair",
	"sys_enter_bind",
	"sys_exit_bind",
	"sys_enter_listen",
	"sys_exit_listen",
	"sys_enter_accept4",
	"sys_exit_accept4",
	"sys_enter_accept",
	"sys_exit_accept",
	"sys_enter_connect",
	"sys_exit_connect",
	"sys_enter_getsockname",
	"sys_exit_getsockname",
	"sys_enter_getpeername",
	"sys_exit_getpeername",
	"sys_enter_sendto",
	"sys_exit_sendto",
	"sys_enter_recvfrom",
	"sys_exit_recvfrom",
	"sys_enter_setsockopt",
	"sys_exit_setsockopt",
	"sys_enter_getsockopt",
	"sys_exit_getsockopt",
	"sys_enter_shutdown",
	"sys_exit_shutdown",
	"sys_enter_sendmsg",
	"sys_exit_sendmsg",
	"sys_enter_sendmmsg",
	"sys_exit_sendmmsg",
	"sys_enter_recvmsg",
	"sys_exit_recvmsg",
	"sys_enter_recvmmsg",
	"sys_exit_recvmmsg",
	"sys_enter_getrandom",
	"sys_exit_getrandom",
	"sys_enter_io_uring_register",
	"sys_exit_io_uring_register",
	"sys_enter_io_uring_enter",
	"sys_exit_io_uring_enter",
	"sys_enter_io_uring_setup",
	"sys_exit_io_uring_setup",
	"sys_enter_ioprio_set",
	"sys_exit_ioprio_set",
	"sys_enter_ioprio_get",
	"sys_exit_ioprio_get",
	"sys_enter_landlock_create_ruleset",
	"sys_exit_landlock_create_ruleset",
	"sys_enter_landlock_add_rule",
	"sys_exit_landlock_add_rule",
	"sys_enter_landlock_restrict_self",
	"sys_exit_landlock_restrict_self",
	"sys_enter_lsm_set_self_attr",
	"sys_exit_lsm_set_self_attr",
	"sys_enter_lsm_get_self_attr",
	"sys_exit_lsm_get_self_attr",
	"sys_enter_lsm_list_modules",
	"sys_exit_lsm_list_modules",
	"sys_enter_add_key",
	"sys_exit_add_key",
	"sys_enter_request_key",
	"sys_exit_request_key",
	"sys_enter_keyctl",
	"sys_exit_keyctl",
	"sys_enter_mq_open",
	"sys_exit_mq_open",
	"sys_enter_mq_unlink",
	"sys_exit_mq_unlink",
	"sys_enter_mq_timedsend",
	"sys_exit_mq_timedsend",
	"sys_enter_mq_timedreceive",
	"sys_exit_mq_timedreceive",
	"sys_enter_mq_notify",
	"sys_exit_mq_notify",
	"sys_enter_mq_getsetattr",
	"sys_exit_mq_getsetattr",
	"sys_enter_shmget",
	"sys_exit_shmget",
	"sys_enter_shmctl",
	"sys_exit_shmctl",
	"sys_enter_shmat",
	"sys_exit_shmat",
	"sys_enter_shmdt",
	"sys_exit_shmdt",
	"sys_enter_semget",
	"sys_exit_semget",
	"sys_enter_semctl",
	"sys_exit_semctl",
	"sys_enter_semtimedop",
	"sys_exit_semtimedop",
	"sys_enter_semop",
	"sys_exit_semop",
	"sys_enter_msgget",
	"sys_exit_msgget",
	"sys_enter_msgctl",
	"sys_exit_msgctl",
	"sys_enter_msgsnd",
	"sys_exit_msgsnd",
	"sys_enter_msgrcv",
	"sys_exit_msgrcv",
	"sys_enter_quotactl",
	"sys_exit_quotactl",
	"sys_enter_quotactl_fd",
	"sys_exit_quotactl_fd",
	"sys_enter_name_to_handle_at",
	"sys_exit_name_to_handle_at",
	"sys_enter_open_by_handle_at",
	"sys_exit_open_by_handle_at",
	"sys_enter_flock",
	"sys_exit_flock",
	"sys_enter_io_setup",
	"sys_exit_io_setup",
	"sys_enter_io_destroy",
	"sys_exit_io_destroy",
	"sys_enter_io_submit",
	"sys_exit_io_submit",
	"sys_enter_io_cancel",
	"sys_exit_io_cancel",
	"sys_enter_io_getevents",
	"sys_exit_io_getevents",
	"sys_enter_io_pgetevents",
	"sys_exit_io_pgetevents",
	"sys_enter_userfaultfd",
	"sys_exit_userfaultfd",
	"sys_enter_eventfd2",
	"sys_exit_eventfd2",
	"sys_enter_eventfd",
	"sys_exit_eventfd",
	"sys_enter_timerfd_create",
	"sys_exit_timerfd_create",
	"sys_enter_timerfd_settime",
	"sys_exit_timerfd_settime",
	"sys_enter_timerfd_gettime",
	"sys_exit_timerfd_gettime",
	"sys_enter_signalfd4",
	"sys_exit_signalfd4",
	"sys_enter_signalfd",
	"sys_exit_signalfd",
	"sys_enter_epoll_create1",
	"sys_exit_epoll_create1",
	"sys_enter_epoll_create",
	"sys_exit_epoll_create",
	"sys_enter_epoll_ctl",
	"sys_exit_epoll_ctl",
	"sys_enter_epoll_wait",
	"sys_exit_epoll_wait",
	"sys_enter_epoll_pwait",
	"sys_exit_epoll_pwait",
	"sys_enter_epoll_pwait2",
	"sys_exit_epoll_pwait2",
	"sys_enter_fanotify_init",
	"sys_exit_fanotify_init",
	"sys_enter_fanotify_mark",
	"sys_exit_fanotify_mark",
	"sys_enter_inotify_init1",
	"sys_exit_inotify_init1",
	"sys_enter_inotify_init",
	"sys_exit_inotify_init",
	"sys_enter_inotify_add_watch",
	"sys_exit_inotify_add_watch",
	"sys_enter_inotify_rm_watch",
	"sys_exit_inotify_rm_watch",
	"sys_enter_file_getattr",
	"sys_exit_file_getattr",
	"sys_enter_file_setattr",
	"sys_exit_file_setattr",
	"sys_enter_fsopen",
	"sys_exit_fsopen",
	"sys_enter_fspick",
	"sys_exit_fspick",
	"sys_enter_fsconfig",
	"sys_exit_fsconfig",
	"sys_enter_statfs",
	"sys_exit_statfs",
	"sys_enter_fstatfs",
	"sys_exit_fstatfs",
	"sys_enter_ustat",
	"sys_exit_ustat",
	"sys_enter_getcwd",
	"sys_exit_getcwd",
	"sys_enter_utimensat",
	"sys_exit_utimensat",
	"sys_enter_futimesat",
	"sys_exit_futimesat",
	"sys_enter_utimes",
	"sys_exit_utimes",
	"sys_enter_utime",
	"sys_exit_utime",
	"sys_enter_sync",
	"sys_exit_sync",
	"sys_enter_syncfs",
	"sys_exit_syncfs",
	"sys_enter_fsync",
	"sys_exit_fsync",
	"sys_enter_fdatasync",
	"sys_exit_fdatasync",
	"sys_enter_sync_file_range",
	"sys_exit_sync_file_range",
	"sys_enter_vmsplice",
	"sys_exit_vmsplice",
	"sys_enter_splice",
	"sys_exit_splice",
	"sys_enter_tee",
	"sys_exit_tee",
	"sys_enter_setxattrat",
	"sys_exit_setxattrat",
	"sys_enter_setxattr",
	"sys_exit_setxattr",
	"sys_enter_lsetxattr",
	"sys_exit_lsetxattr",
	"sys_enter_fsetxattr",
	"sys_exit_fsetxattr",
	"sys_enter_getxattrat",
	"sys_exit_getxattrat",
	"sys_enter_getxattr",
	"sys_exit_getxattr",
	"sys_enter_lgetxattr",
	"sys_exit_lgetxattr",
	"sys_enter_fgetxattr",
	"sys_exit_fgetxattr",
	"sys_enter_listxattrat",
	"sys_exit_listxattrat",
	"sys_enter_listxattr",
	"sys_exit_listxattr",
	"sys_enter_llistxattr",
	"sys_exit_llistxattr",
	"sys_enter_flistxattr",
	"sys_exit_flistxattr",
	"sys_enter_removexattrat",
	"sys_exit_removexattrat",
	"sys_enter_removexattr",
	"sys_exit_removexattr",
	"sys_enter_lremovexattr",
	"sys_exit_lremovexattr",
	"sys_enter_fremovexattr",
	"sys_exit_fremovexattr",
	"sys_enter_umount",
	"sys_exit_umount",
	"sys_enter_open_tree",
	"sys_exit_open_tree",
	"sys_enter_mount",
	"sys_exit_mount",
	"sys_enter_fsmount",
	"sys_exit_fsmount",
	"sys_enter_move_mount",
	"sys_exit_move_mount",
	"sys_enter_pivot_root",
	"sys_exit_pivot_root",
	"sys_enter_mount_setattr",
	"sys_exit_mount_setattr",
	"sys_enter_open_tree_attr",
	"sys_exit_open_tree_attr",
	"sys_enter_statmount",
	"sys_exit_statmount",
	"sys_enter_listmount",
	"sys_exit_listmount",
	"sys_enter_sysfs",
	"sys_exit_sysfs",
	"sys_enter_close_range",
	"sys_exit_close_range",
	"sys_enter_dup3",
	"sys_exit_dup3",
	"sys_enter_dup2",
	"sys_exit_dup2",
	"sys_enter_dup",
	"sys_exit_dup",
	"sys_enter_select",
	"sys_exit_select",
	"sys_enter_pselect6",
	"sys_exit_pselect6",
	"sys_enter_poll",
	"sys_exit_poll",
	"sys_enter_ppoll",
	"sys_exit_ppoll",
	"sys_enter_getdents",
	"sys_exit_getdents",
	"sys_enter_getdents64",
	"sys_exit_getdents64",
	"sys_enter_ioctl",
	"sys_exit_ioctl",
	"sys_enter_fcntl",
	"sys_exit_fcntl",
	"sys_enter_mknodat",
	"sys_exit_mknodat",
	"sys_enter_mknod",
	"sys_exit_mknod",
	"sys_enter_mkdirat",
	"sys_exit_mkdirat",
	"sys_enter_mkdir",
	"sys_exit_mkdir",
	"sys_enter_rmdir",
	"sys_exit_rmdir",
	"sys_enter_unlinkat",
	"sys_exit_unlinkat",
	"sys_enter_unlink",
	"sys_exit_unlink",
	"sys_enter_symlinkat",
	"sys_exit_symlinkat",
	"sys_enter_symlink",
	"sys_exit_symlink",
	"sys_enter_linkat",
	"sys_exit_linkat",
	"sys_enter_link",
	"sys_exit_link",
	"sys_enter_renameat2",
	"sys_exit_renameat2",
	"sys_enter_renameat",
	"sys_exit_renameat",
	"sys_enter_rename",
	"sys_exit_rename",
	"sys_enter_pipe2",
	"sys_exit_pipe2",
	"sys_enter_pipe",
	"sys_exit_pipe",
	"sys_enter_execve",
	"sys_exit_execve",
	"sys_enter_execveat",
	"sys_exit_execveat",
	"sys_enter_newstat",
	"sys_exit_newstat",
	"sys_enter_newlstat",
	"sys_exit_newlstat",
	"sys_enter_newfstatat",
	"sys_exit_newfstatat",
	"sys_enter_newfstat",
	"sys_exit_newfstat",
	"sys_enter_readlinkat",
	"sys_exit_readlinkat",
	"sys_enter_readlink",
	"sys_exit_readlink",
	"sys_enter_statx",
	"sys_exit_statx",
	"sys_enter_lseek",
	"sys_exit_lseek",
	"sys_enter_read",
	"sys_exit_read",
	"sys_enter_write",
	"sys_exit_write",
	"sys_enter_pread64",
	"sys_exit_pread64",
	"sys_enter_pwrite64",
	"sys_exit_pwrite64",
	"sys_enter_readv",
	"sys_exit_readv",
	"sys_enter_writev",
	"sys_exit_writev",
	"sys_enter_preadv",
	"sys_exit_preadv",
	"sys_enter_preadv2",
	"sys_exit_preadv2",
	"sys_enter_pwritev",
	"sys_exit_pwritev",
	"sys_enter_pwritev2",
	"sys_exit_pwritev2",
	"sys_enter_sendfile64",
	"sys_exit_sendfile64",
	"sys_enter_copy_file_range",
	"sys_exit_copy_file_range",
	"sys_enter_truncate",
	"sys_exit_truncate",
	"sys_enter_ftruncate",
	"sys_exit_ftruncate",
	"sys_enter_fallocate",
	"sys_exit_fallocate",
	"sys_enter_faccessat",
	"sys_exit_faccessat",
	"sys_enter_faccessat2",
	"sys_exit_faccessat2",
	"sys_enter_access",
	"sys_exit_access",
	"sys_enter_chdir",
	"sys_exit_chdir",
	"sys_enter_fchdir",
	"sys_exit_fchdir",
	"sys_enter_chroot",
	"sys_exit_chroot",
	"sys_enter_fchmod",
	"sys_exit_fchmod",
	"sys_enter_fchmodat2",
	"sys_exit_fchmodat2",
	"sys_enter_fchmodat",
	"sys_exit_fchmodat",
	"sys_enter_chmod",
	"sys_exit_chmod",
	"sys_enter_fchownat",
	"sys_exit_fchownat",
	"sys_enter_chown",
	"sys_exit_chown",
	"sys_enter_lchown",
	"sys_exit_lchown",
	"sys_enter_fchown",
	"sys_exit_fchown",
	"sys_enter_open",
	"sys_exit_open",
	"sys_enter_openat",
	"sys_exit_openat",
	"sys_enter_openat2",
	"sys_exit_openat2",
	"sys_enter_creat",
	"sys_exit_creat",
	"sys_enter_close",
	"sys_exit_close",
	"sys_enter_vhangup",
	"sys_exit_vhangup",
	"sys_enter_memfd_create",
	"sys_exit_memfd_create",
	"sys_enter_memfd_secret",
	"sys_exit_memfd_secret",
	"sys_enter_move_pages",
	"sys_exit_move_pages",
	"sys_enter_set_mempolicy_home_node",
	"sys_exit_set_mempolicy_home_node",
	"sys_enter_mbind",
	"sys_exit_mbind",
	"sys_enter_set_mempolicy",
	"sys_exit_set_mempolicy",
	"sys_enter_migrate_pages",
	"sys_exit_migrate_pages",
	"sys_enter_get_mempolicy",
	"sys_exit_get_mempolicy",
	"sys_enter_swapoff",
	"sys_exit_swapoff",
	"sys_enter_swapon",
	"sys_exit_swapon",
	"sys_enter_madvise",
	"sys_exit_madvise",
	"sys_enter_process_madvise",
	"sys_exit_process_madvise",
	"sys_enter_mseal",
	"sys_exit_mseal",
	"sys_enter_process_vm_readv",
	"sys_exit_process_vm_readv",
	"sys_enter_process_vm_writev",
	"sys_exit_process_vm_writev",
	"sys_enter_msync",
	"sys_exit_msync",
	"sys_enter_mremap",
	"sys_exit_mremap",
	"sys_enter_mprotect",
	"sys_exit_mprotect",
	"sys_enter_pkey_mprotect",
	"sys_exit_pkey_mprotect",
	"sys_enter_pkey_alloc",
	"sys_exit_pkey_alloc",
	"sys_enter_pkey_free",
	"sys_exit_pkey_free",
	"sys_enter_brk",
	"sys_exit_brk",
	"sys_enter_munmap",
	"sys_exit_munmap",
	"sys_enter_remap_file_pages",
	"sys_exit_remap_file_pages",
	"sys_enter_mlock",
	"sys_exit_mlock",
	"sys_enter_mlock2",
	"sys_exit_mlock2",
	"sys_enter_munlock",
	"sys_exit_munlock",
	"sys_enter_mlockall",
	"sys_exit_mlockall",
	"sys_enter_munlockall",
	"sys_exit_munlockall",
	"sys_enter_mincore",
	"sys_exit_mincore",
	"sys_enter_readahead",
	"sys_exit_readahead",
	"sys_enter_fadvise64",
	"sys_exit_fadvise64",
	"sys_enter_process_mrelease",
	"sys_exit_process_mrelease",
	"sys_enter_cachestat",
	"sys_exit_cachestat",
	"sys_enter_rseq",
	"sys_exit_rseq",
	"sys_enter_perf_event_open",
	"sys_exit_perf_event_open",
	"sys_enter_bpf",
	"sys_exit_bpf",
	"sys_enter_seccomp",
	"sys_exit_seccomp",
	"sys_enter_kexec_file_load",
	"sys_exit_kexec_file_load",
	"sys_enter_kexec_load",
	"sys_exit_kexec_load",
	"sys_enter_acct",
	"sys_exit_acct",
	"sys_enter_set_robust_list",
	"sys_exit_set_robust_list",
	"sys_enter_get_robust_list",
	"sys_exit_get_robust_list",
	"sys_enter_futex",
	"sys_exit_futex",
	"sys_enter_futex_waitv",
	"sys_exit_futex_waitv",
	"sys_enter_futex_wake",
	"sys_exit_futex_wake",
	"sys_enter_futex_wait",
	"sys_exit_futex_wait",
	"sys_enter_futex_requeue",
	"sys_exit_futex_requeue",
	"sys_enter_getitimer",
	"sys_exit_getitimer",
	"sys_enter_alarm",
	"sys_exit_alarm",
	"sys_enter_setitimer",
	"sys_exit_setitimer",
	"sys_enter_timer_create",
	"sys_exit_timer_create",
	"sys_enter_timer_gettime",
	"sys_exit_timer_gettime",
	"sys_enter_timer_getoverrun",
	"sys_exit_timer_getoverrun",
	"sys_enter_timer_settime",
	"sys_exit_timer_settime",
	"sys_enter_timer_delete",
	"sys_exit_timer_delete",
	"sys_enter_clock_settime",
	"sys_exit_clock_settime",
	"sys_enter_clock_gettime",
	"sys_exit_clock_gettime",
	"sys_enter_clock_adjtime",
	"sys_exit_clock_adjtime",
	"sys_enter_clock_getres",
	"sys_exit_clock_getres",
	"sys_enter_clock_nanosleep",
	"sys_exit_clock_nanosleep",
	"sys_enter_nanosleep",
	"sys_exit_nanosleep",
	"sys_enter_time",
	"sys_exit_time",
	"sys_enter_gettimeofday",
	"sys_exit_gettimeofday",
	"sys_enter_settimeofday",
	"sys_exit_settimeofday",
	"sys_enter_adjtimex",
	"sys_exit_adjtimex",
	"sys_enter_kcmp",
	"sys_exit_kcmp",
	"sys_enter_delete_module",
	"sys_exit_delete_module",
	"sys_enter_init_module",
	"sys_exit_init_module",
	"sys_enter_finit_module",
	"sys_exit_finit_module",
	"sys_enter_syslog",
	"sys_exit_syslog",
	"sys_enter_membarrier",
	"sys_exit_membarrier",
	"sys_enter_sched_setscheduler",
	"sys_exit_sched_setscheduler",
	"sys_enter_sched_setparam",
	"sys_exit_sched_setparam",
	"sys_enter_sched_setattr",
	"sys_exit_sched_setattr",
	"sys_enter_sched_getscheduler",
	"sys_exit_sched_getscheduler",
	"sys_enter_sched_getparam",
	"sys_exit_sched_getparam",
	"sys_enter_sched_getattr",
	"sys_exit_sched_getattr",
	"sys_enter_sched_setaffinity",
	"sys_exit_sched_setaffinity",
	"sys_enter_sched_getaffinity",
	"sys_exit_sched_getaffinity",
	"sys_enter_sched_yield",
	"sys_exit_sched_yield",
	"sys_enter_sched_get_priority_max",
	"sys_exit_sched_get_priority_max",
	"sys_enter_sched_get_priority_min",
	"sys_exit_sched_get_priority_min",
	"sys_enter_sched_rr_get_interval",
	"sys_exit_sched_rr_get_interval",
	"sys_enter_getgroups",
	"sys_exit_getgroups",
	"sys_enter_setgroups",
	"sys_exit_setgroups",
	"sys_enter_reboot",
	"sys_exit_reboot",
	"sys_enter_listns",
	"sys_exit_listns",
	"sys_enter_setns",
	"sys_exit_setns",
	"sys_enter_pidfd_open",
	"sys_exit_pidfd_open",
	"sys_enter_pidfd_getfd",
	"sys_exit_pidfd_getfd",
	"sys_enter_setpriority",
	"sys_exit_setpriority",
	"sys_enter_getpriority",
	"sys_exit_getpriority",
	"sys_enter_setregid",
	"sys_exit_setregid",
	"sys_enter_setgid",
	"sys_exit_setgid",
	"sys_enter_setreuid",
	"sys_exit_setreuid",
	"sys_enter_setuid",
	"sys_exit_setuid",
	"sys_enter_setresuid",
	"sys_exit_setresuid",
	"sys_enter_getresuid",
	"sys_exit_getresuid",
	"sys_enter_setresgid",
	"sys_exit_setresgid",
	"sys_enter_getresgid",
	"sys_exit_getresgid",
	"sys_enter_setfsuid",
	"sys_exit_setfsuid",
	"sys_enter_setfsgid",
	"sys_exit_setfsgid",
	"sys_enter_getpid",
	"sys_exit_getpid",
	"sys_enter_gettid",
	"sys_exit_gettid",
	"sys_enter_getppid",
	"sys_exit_getppid",
	"sys_enter_getuid",
	"sys_exit_getuid",
	"sys_enter_geteuid",
	"sys_exit_geteuid",
	"sys_enter_getgid",
	"sys_exit_getgid",
	"sys_enter_getegid",
	"sys_exit_getegid",
	"sys_enter_times",
	"sys_exit_times",
	"sys_enter_setpgid",
	"sys_exit_setpgid",
	"sys_enter_getpgid",
	"sys_exit_getpgid",
	"sys_enter_getpgrp",
	"sys_exit_getpgrp",
	"sys_enter_getsid",
	"sys_exit_getsid",
	"sys_enter_setsid",
	"sys_exit_setsid",
	"sys_enter_newuname",
	"sys_exit_newuname",
	"sys_enter_sethostname",
	"sys_exit_sethostname",
	"sys_enter_setdomainname",
	"sys_exit_setdomainname",
	"sys_enter_getrlimit",
	"sys_exit_getrlimit",
	"sys_enter_prlimit64",
	"sys_exit_prlimit64",
	"sys_enter_setrlimit",
	"sys_exit_setrlimit",
	"sys_enter_getrusage",
	"sys_exit_getrusage",
	"sys_enter_umask",
	"sys_exit_umask",
	"sys_enter_prctl",
	"sys_exit_prctl",
	"sys_enter_getcpu",
	"sys_exit_getcpu",
	"sys_enter_sysinfo",
	"sys_exit_sysinfo",
	"sys_enter_restart_syscall",
	"sys_exit_restart_syscall",
	"sys_enter_rt_sigprocmask",
	"sys_exit_rt_sigprocmask",
	"sys_enter_rt_sigpending",
	"sys_exit_rt_sigpending",
	"sys_enter_rt_sigtimedwait",
	"sys_exit_rt_sigtimedwait",
	"sys_enter_kill",
	"sys_exit_kill",
	"sys_enter_pidfd_send_signal",
	"sys_exit_pidfd_send_signal",
	"sys_enter_tgkill",
	"sys_exit_tgkill",
	"sys_enter_tkill",
	"sys_exit_tkill",
	"sys_enter_rt_sigqueueinfo",
	"sys_exit_rt_sigqueueinfo",
	"sys_enter_rt_tgsigqueueinfo",
	"sys_exit_rt_tgsigqueueinfo",
	"sys_enter_sigaltstack",
	"sys_exit_sigaltstack",
	"sys_enter_rt_sigaction",
	"sys_exit_rt_sigaction",
	"sys_enter_pause",
	"sys_exit_pause",
	"sys_enter_rt_sigsuspend",
	"sys_exit_rt_sigsuspend",
	"sys_enter_ptrace",
	"sys_exit_ptrace",
	"sys_enter_capget",
	"sys_exit_capget",
	"sys_enter_capset",
	"sys_exit_capset",
	"sys_enter_exit",
	"sys_exit_exit",
	"sys_enter_exit_group",
	"sys_exit_exit_group",
	"sys_enter_waitid",
	"sys_exit_waitid",
	"sys_enter_wait4",
	"sys_exit_wait4",
	"sys_enter_personality",
	"sys_exit_personality",
	"sys_enter_set_tid_address",
	"sys_exit_set_tid_address",
	"sys_enter_fork",
	"sys_exit_fork",
	"sys_enter_vfork",
	"sys_exit_vfork",
	"sys_enter_clone",
	"sys_exit_clone",
	"sys_enter_clone3",
	"sys_exit_clone3",
	"sys_enter_unshare",
	"sys_exit_unshare",
	"sys_enter_map_shadow_stack",
	"sys_exit_map_shadow_stack",
	"sys_enter_uretprobe",
	"sys_exit_uretprobe",
	"sys_enter_uprobe",
	"sys_exit_uprobe",
	"sys_enter_arch_prctl",
	"sys_exit_arch_prctl",
	"sys_enter_mmap",
	"sys_exit_mmap",
	"sys_enter_modify_ldt",
	"sys_exit_modify_ldt",
	"sys_enter_ioperm",
	"sys_exit_ioperm",
	"sys_enter_iopl",
	"sys_exit_iopl",
	"sys_enter_rt_sigreturn",
	"sys_exit_rt_sigreturn",
}

var syscallFamilies = map[string]string{
	"accept":                  "Network",
	"accept4":                 "Network",
	"access":                  "FS",
	"acct":                    "Misc",
	"add_key":                 "Security",
	"adjtimex":                "Misc",
	"alarm":                   "Misc",
	"arch_prctl":              "Process",
	"bind":                    "Network",
	"bpf":                     "Security",
	"brk":                     "Memory",
	"cachestat":               "FS",
	"capget":                  "Security",
	"capset":                  "Security",
	"chdir":                   "FS",
	"chmod":                   "FS",
	"chown":                   "FS",
	"chroot":                  "FS",
	"clock_adjtime":           "Time",
	"clock_getres":            "Time",
	"clock_gettime":           "Time",
	"clock_nanosleep":         "Time",
	"clock_settime":           "Time",
	"clone":                   "Process",
	"clone3":                  "Process",
	"close":                   "FS",
	"close_range":             "FS",
	"connect":                 "Network",
	"copy_file_range":         "FS",
	"creat":                   "FS",
	"delete_module":           "Security",
	"dup":                     "FS",
	"dup2":                    "FS",
	"dup3":                    "FS",
	"epoll_create":            "Polling",
	"epoll_create1":           "Polling",
	"epoll_ctl":               "Polling",
	"epoll_pwait":             "Polling",
	"epoll_pwait2":            "Polling",
	"epoll_wait":              "Polling",
	"eventfd":                 "IPC",
	"eventfd2":                "IPC",
	"execve":                  "Process",
	"execveat":                "Process",
	"exit":                    "Process",
	"exit_group":              "Process",
	"faccessat":               "FS",
	"faccessat2":              "FS",
	"fadvise64":               "FS",
	"fallocate":               "FS",
	"fanotify_init":           "Misc",
	"fanotify_mark":           "Misc",
	"fchdir":                  "FS",
	"fchmod":                  "FS",
	"fchmodat":                "FS",
	"fchmodat2":               "FS",
	"fchown":                  "FS",
	"fchownat":                "FS",
	"fcntl":                   "FS",
	"fdatasync":               "FS",
	"fgetxattr":               "FS",
	"file_getattr":            "Misc",
	"file_setattr":            "Misc",
	"finit_module":            "Security",
	"flistxattr":              "FS",
	"flock":                   "FS",
	"fork":                    "Process",
	"fremovexattr":            "FS",
	"fsconfig":                "FS",
	"fsetxattr":               "FS",
	"fsmount":                 "FS",
	"fsopen":                  "FS",
	"fspick":                  "FS",
	"fstatfs":                 "FS",
	"fsync":                   "FS",
	"ftruncate":               "FS",
	"futex":                   "Misc",
	"futex_requeue":           "Misc",
	"futex_wait":              "Misc",
	"futex_waitv":             "Misc",
	"futex_wake":              "Misc",
	"futimesat":               "FS",
	"get_mempolicy":           "Security",
	"get_robust_list":         "Misc",
	"getcpu":                  "Misc",
	"getcwd":                  "FS",
	"getdents":                "FS",
	"getdents64":              "FS",
	"getegid":                 "Process",
	"geteuid":                 "Process",
	"getgid":                  "Process",
	"getgroups":               "Process",
	"getitimer":               "Time",
	"getpeername":             "Network",
	"getpgid":                 "Process",
	"getpgrp":                 "Process",
	"getpid":                  "Process",
	"getppid":                 "Process",
	"getpriority":             "Process",
	"getrandom":               "Security",
	"getresgid":               "Process",
	"getresuid":               "Process",
	"getrlimit":               "Process",
	"getrusage":               "Process",
	"getsid":                  "Process",
	"getsockname":             "Network",
	"getsockopt":              "Network",
	"gettid":                  "Process",
	"gettimeofday":            "Time",
	"getuid":                  "Process",
	"getxattr":                "FS",
	"getxattrat":              "FS",
	"init_module":             "Security",
	"inotify_add_watch":       "IPC",
	"inotify_init":            "IPC",
	"inotify_init1":           "IPC",
	"inotify_rm_watch":        "IPC",
	"io_cancel":               "AIO",
	"io_destroy":              "AIO",
	"io_getevents":            "AIO",
	"io_pgetevents":           "AIO",
	"io_setup":                "AIO",
	"io_submit":               "AIO",
	"io_uring_enter":          "AIO",
	"io_uring_register":       "AIO",
	"io_uring_setup":          "AIO",
	"ioctl":                   "FS",
	"ioperm":                  "Misc",
	"iopl":                    "Misc",
	"ioprio_get":              "Misc",
	"ioprio_set":              "Misc",
	"kcmp":                    "Process",
	"kexec_file_load":         "Security",
	"kexec_load":              "Misc",
	"keyctl":                  "Security",
	"kill":                    "Signals",
	"landlock_add_rule":       "Security",
	"landlock_create_ruleset": "Security",
	"landlock_restrict_self":  "Security",
	"lchown":                  "FS",
	"lgetxattr":               "FS",
	"link":                    "FS",
	"linkat":                  "FS",
	"listen":                  "Network",
	"listmount":               "FS",
	"listns":                  "FS",
	"listxattr":               "FS",
	"listxattrat":             "FS",
	"llistxattr":              "FS",
	"lremovexattr":            "FS",
	"lseek":                   "FS",
	"lsetxattr":               "FS",
	"lsm_get_self_attr":       "Misc",
	"lsm_list_modules":        "Misc",
	"lsm_set_self_attr":       "Misc",
	"madvise":                 "Memory",
	"map_shadow_stack":        "Memory",
	"mbind":                   "Memory",
	"membarrier":              "Memory",
	"memfd_create":            "IPC",
	"memfd_secret":            "IPC",
	"migrate_pages":           "Memory",
	"mincore":                 "Memory",
	"mkdir":                   "FS",
	"mkdirat":                 "FS",
	"mknod":                   "FS",
	"mknodat":                 "FS",
	"mlock":                   "Memory",
	"mlock2":                  "Memory",
	"mlockall":                "Memory",
	"mmap":                    "Memory",
	"modify_ldt":              "Misc",
	"mount":                   "FS",
	"mount_setattr":           "FS",
	"move_mount":              "FS",
	"move_pages":              "Memory",
	"mprotect":                "Memory",
	"mq_getsetattr":           "IPC",
	"mq_notify":               "IPC",
	"mq_open":                 "IPC",
	"mq_timedreceive":         "IPC",
	"mq_timedsend":            "IPC",
	"mq_unlink":               "IPC",
	"mremap":                  "Memory",
	"mseal":                   "Memory",
	"msgctl":                  "IPC",
	"msgget":                  "IPC",
	"msgrcv":                  "IPC",
	"msgsnd":                  "IPC",
	"msync":                   "FS",
	"munlock":                 "Memory",
	"munlockall":              "Memory",
	"munmap":                  "Memory",
	"name_to_handle_at":       "FS",
	"nanosleep":               "Time",
	"newfstat":                "FS",
	"newfstatat":              "FS",
	"newlstat":                "FS",
	"newstat":                 "FS",
	"newuname":                "Misc",
	"open":                    "FS",
	"open_by_handle_at":       "FS",
	"open_tree":               "FS",
	"open_tree_attr":          "FS",
	"openat":                  "FS",
	"openat2":                 "FS",
	"pause":                   "Signals",
	"perf_event_open":         "Security",
	"personality":             "Process",
	"pidfd_getfd":             "IPC",
	"pidfd_open":              "IPC",
	"pidfd_send_signal":       "IPC",
	"pipe":                    "IPC",
	"pipe2":                   "IPC",
	"pivot_root":              "Process",
	"pkey_alloc":              "Memory",
	"pkey_free":               "Memory",
	"pkey_mprotect":           "Memory",
	"poll":                    "Polling",
	"ppoll":                   "Polling",
	"prctl":                   "Process",
	"pread64":                 "FS",
	"preadv":                  "FS",
	"preadv2":                 "FS",
	"prlimit64":               "Process",
	"process_madvise":         "Memory",
	"process_mrelease":        "Memory",
	"process_vm_readv":        "Memory",
	"process_vm_writev":       "Memory",
	"pselect6":                "Polling",
	"ptrace":                  "Security",
	"pwrite64":                "FS",
	"pwritev":                 "FS",
	"pwritev2":                "FS",
	"quotactl":                "FS",
	"quotactl_fd":             "FS",
	"read":                    "FS",
	"readahead":               "FS",
	"readlink":                "FS",
	"readlinkat":              "FS",
	"readv":                   "FS",
	"reboot":                  "Process",
	"recvfrom":                "Network",
	"recvmmsg":                "Network",
	"recvmsg":                 "Network",
	"remap_file_pages":        "Memory",
	"removexattr":             "FS",
	"removexattrat":           "FS",
	"rename":                  "FS",
	"renameat":                "FS",
	"renameat2":               "FS",
	"request_key":             "Security",
	"restart_syscall":         "Process",
	"rmdir":                   "FS",
	"rseq":                    "Misc",
	"rt_sigaction":            "Signals",
	"rt_sigpending":           "Signals",
	"rt_sigprocmask":          "Signals",
	"rt_sigqueueinfo":         "Signals",
	"rt_sigreturn":            "Signals",
	"rt_sigsuspend":           "Signals",
	"rt_sigtimedwait":         "Signals",
	"rt_tgsigqueueinfo":       "Signals",
	"sched_get_priority_max":  "Sched",
	"sched_get_priority_min":  "Sched",
	"sched_getaffinity":       "Sched",
	"sched_getattr":           "Sched",
	"sched_getparam":          "Sched",
	"sched_getscheduler":      "Sched",
	"sched_rr_get_interval":   "Sched",
	"sched_setaffinity":       "Sched",
	"sched_setattr":           "Sched",
	"sched_setparam":          "Sched",
	"sched_setscheduler":      "Sched",
	"sched_yield":             "Sched",
	"seccomp":                 "Security",
	"select":                  "Polling",
	"semctl":                  "IPC",
	"semget":                  "IPC",
	"semop":                   "IPC",
	"semtimedop":              "IPC",
	"sendfile64":              "Network",
	"sendmmsg":                "Network",
	"sendmsg":                 "Network",
	"sendto":                  "Network",
	"set_mempolicy":           "Memory",
	"set_mempolicy_home_node": "Memory",
	"set_robust_list":         "Misc",
	"set_tid_address":         "Process",
	"setdomainname":           "Misc",
	"setfsgid":                "Process",
	"setfsuid":                "Process",
	"setgid":                  "Process",
	"setgroups":               "Process",
	"sethostname":             "Misc",
	"setitimer":               "Time",
	"setns":                   "Process",
	"setpgid":                 "Process",
	"setpriority":             "Process",
	"setregid":                "Process",
	"setresgid":               "Process",
	"setresuid":               "Process",
	"setreuid":                "Process",
	"setrlimit":               "Process",
	"setsid":                  "Process",
	"setsockopt":              "Network",
	"settimeofday":            "Time",
	"setuid":                  "Process",
	"setxattr":                "FS",
	"setxattrat":              "FS",
	"shmat":                   "IPC",
	"shmctl":                  "IPC",
	"shmdt":                   "IPC",
	"shmget":                  "IPC",
	"shutdown":                "Network",
	"sigaltstack":             "Signals",
	"signalfd":                "IPC",
	"signalfd4":               "IPC",
	"socket":                  "Network",
	"socketpair":              "Network",
	"splice":                  "Network",
	"statfs":                  "FS",
	"statmount":               "FS",
	"statx":                   "FS",
	"swapoff":                 "FS",
	"swapon":                  "FS",
	"symlink":                 "FS",
	"symlinkat":               "FS",
	"sync":                    "FS",
	"sync_file_range":         "FS",
	"syncfs":                  "FS",
	"sysfs":                   "Misc",
	"sysinfo":                 "Misc",
	"syslog":                  "Misc",
	"tee":                     "Network",
	"tgkill":                  "Signals",
	"time":                    "Time",
	"timer_create":            "Time",
	"timer_delete":            "Time",
	"timer_getoverrun":        "Time",
	"timer_gettime":           "Time",
	"timer_settime":           "Time",
	"timerfd_create":          "IPC",
	"timerfd_gettime":         "IPC",
	"timerfd_settime":         "IPC",
	"times":                   "Time",
	"tkill":                   "Signals",
	"truncate":                "FS",
	"umask":                   "Process",
	"umount":                  "FS",
	"unlink":                  "FS",
	"unlinkat":                "FS",
	"unshare":                 "Process",
	"uprobe":                  "Misc",
	"uretprobe":               "Misc",
	"userfaultfd":             "IPC",
	"ustat":                   "FS",
	"utime":                   "Misc",
	"utimensat":               "FS",
	"utimes":                  "Misc",
	"vfork":                   "Process",
	"vhangup":                 "Process",
	"vmsplice":                "Misc",
	"wait4":                   "Process",
	"waitid":                  "Process",
	"write":                   "FS",
	"writev":                  "FS",
}

var syscallKinds = map[string]string{
	"accept":                  "accept",
	"accept4":                 "accept",
	"access":                  "pathname",
	"acct":                    "pathname",
	"add_key":                 "keyctl",
	"adjtimex":                "null",
	"alarm":                   "null",
	"arch_prctl":              "null",
	"bind":                    "fd",
	"bpf":                     "bpf",
	"brk":                     "mem",
	"cachestat":               "fd",
	"capget":                  "null",
	"capset":                  "null",
	"chdir":                   "pathname",
	"chmod":                   "pathname",
	"chown":                   "pathname",
	"chroot":                  "pathname",
	"clock_adjtime":           "null",
	"clock_getres":            "null",
	"clock_gettime":           "null",
	"clock_nanosleep":         "sleep",
	"clock_settime":           "null",
	"clone":                   "proc",
	"clone3":                  "proc",
	"close":                   "fd",
	"close_range":             "fd",
	"connect":                 "fd",
	"copy_file_range":         "fd",
	"creat":                   "pathname",
	"delete_module":           "module",
	"dup":                     "fd",
	"dup2":                    "fd",
	"dup3":                    "dup3",
	"epoll_create":            "eventfd",
	"epoll_create1":           "eventfd",
	"epoll_ctl":               "epoll-ctl",
	"epoll_pwait":             "fd",
	"epoll_pwait2":            "fd",
	"epoll_wait":              "fd",
	"eventfd":                 "eventfd",
	"eventfd2":                "eventfd",
	"execve":                  "exec",
	"execveat":                "exec",
	"exit":                    "null",
	"exit_group":              "null",
	"faccessat":               "pathname",
	"faccessat2":              "pathname",
	"fadvise64":               "fd",
	"fallocate":               "fd",
	"fanotify_init":           "eventfd",
	"fanotify_mark":           "pathname",
	"fchdir":                  "fd",
	"fchmod":                  "fd",
	"fchmodat":                "pathname",
	"fchmodat2":               "pathname",
	"fchown":                  "fd",
	"fchownat":                "pathname",
	"fcntl":                   "fcntl",
	"fdatasync":               "fd",
	"fgetxattr":               "fd",
	"file_getattr":            "pathname",
	"file_setattr":            "pathname",
	"finit_module":            "fd",
	"flistxattr":              "fd",
	"flock":                   "fd",
	"fork":                    "proc",
	"fremovexattr":            "fd",
	"fsconfig":                "fd",
	"fsetxattr":               "fd",
	"fsmount":                 "eventfd",
	"fsopen":                  "eventfd",
	"fspick":                  "pathname",
	"fstatfs":                 "fd",
	"fsync":                   "fd",
	"ftruncate":               "fd",
	"futex":                   "futex",
	"futex_requeue":           "futex",
	"futex_wait":              "futex",
	"futex_waitv":             "futex",
	"futex_wake":              "futex",
	"futimesat":               "pathname",
	"get_mempolicy":           "null",
	"get_robust_list":         "null",
	"getcpu":                  "null",
	"getcwd":                  "null",
	"getdents":                "fd",
	"getdents64":              "fd",
	"getegid":                 "null",
	"geteuid":                 "null",
	"getgid":                  "null",
	"getgroups":               "null",
	"getitimer":               "null",
	"getpeername":             "fd",
	"getpgid":                 "null",
	"getpgrp":                 "null",
	"getpid":                  "null",
	"getppid":                 "null",
	"getpriority":             "null",
	"getrandom":               "null",
	"getresgid":               "null",
	"getresuid":               "null",
	"getrlimit":               "null",
	"getrusage":               "null",
	"getsid":                  "null",
	"getsockname":             "fd",
	"getsockopt":              "fd",
	"gettid":                  "null",
	"gettimeofday":            "null",
	"getuid":                  "null",
	"getxattr":                "pathname",
	"getxattrat":              "pathname",
	"init_module":             "module",
	"inotify_add_watch":       "fd",
	"inotify_init":            "eventfd",
	"inotify_init1":           "eventfd",
	"inotify_rm_watch":        "fd",
	"io_cancel":               "null",
	"io_destroy":              "null",
	"io_getevents":            "null",
	"io_pgetevents":           "null",
	"io_setup":                "null",
	"io_submit":               "null",
	"io_uring_enter":          "fd",
	"io_uring_register":       "fd",
	"io_uring_setup":          "null",
	"ioctl":                   "fd",
	"ioperm":                  "null",
	"iopl":                    "null",
	"ioprio_get":              "null",
	"ioprio_set":              "null",
	"kcmp":                    "two-fd",
	"kexec_file_load":         "fd",
	"kexec_load":              "null",
	"keyctl":                  "keyctl",
	"kill":                    "null",
	"landlock_add_rule":       "null",
	"landlock_create_ruleset": "eventfd",
	"landlock_restrict_self":  "null",
	"lchown":                  "pathname",
	"lgetxattr":               "pathname",
	"link":                    "name",
	"linkat":                  "name",
	"listen":                  "fd",
	"listmount":               "null",
	"listns":                  "null",
	"listxattr":               "pathname",
	"listxattrat":             "pathname",
	"llistxattr":              "pathname",
	"lremovexattr":            "pathname",
	"lseek":                   "fd",
	"lsetxattr":               "pathname",
	"lsm_get_self_attr":       "null",
	"lsm_list_modules":        "null",
	"lsm_set_self_attr":       "null",
	"madvise":                 "mem",
	"map_shadow_stack":        "mem",
	"mbind":                   "null",
	"membarrier":              "null",
	"memfd_create":            "eventfd",
	"memfd_secret":            "eventfd",
	"migrate_pages":           "null",
	"mincore":                 "mem",
	"mkdir":                   "pathname",
	"mkdirat":                 "pathname",
	"mknod":                   "pathname",
	"mknodat":                 "pathname",
	"mlock":                   "mem",
	"mlock2":                  "mem",
	"mlockall":                "null",
	"mmap":                    "fd",
	"modify_ldt":              "null",
	"mount":                   "pathname",
	"mount_setattr":           "pathname",
	"move_mount":              "two-fd",
	"move_pages":              "null",
	"mprotect":                "mem",
	"mq_getsetattr":           "fd",
	"mq_notify":               "fd",
	"mq_open":                 "mq-open",
	"mq_timedreceive":         "fd",
	"mq_timedsend":            "fd",
	"mq_unlink":               "pathname",
	"mremap":                  "mem",
	"mseal":                   "mem",
	"msgctl":                  "sysv-op",
	"msgget":                  "sysv-id",
	"msgrcv":                  "sysv-op",
	"msgsnd":                  "sysv-op",
	"msync":                   "null",
	"munlock":                 "mem",
	"munlockall":              "null",
	"munmap":                  "mem",
	"name_to_handle_at":       "pathname",
	"nanosleep":               "sleep",
	"newfstat":                "fd",
	"newfstatat":              "pathname",
	"newlstat":                "pathname",
	"newstat":                 "pathname",
	"newuname":                "null",
	"open":                    "open",
	"open_by_handle_at":       "open-by-handle-at",
	"open_tree":               "open",
	"open_tree_attr":          "open",
	"openat":                  "open",
	"openat2":                 "open",
	"pause":                   "null",
	"perf_event_open":         "perf-open",
	"personality":             "null",
	"pidfd_getfd":             "fd",
	"pidfd_open":              "pidfd",
	"pidfd_send_signal":       "fd",
	"pipe":                    "pipe",
	"pipe2":                   "pipe",
	"pivot_root":              "pathname",
	"pkey_alloc":              "null",
	"pkey_free":               "null",
	"pkey_mprotect":           "mem",
	"poll":                    "poll",
	"ppoll":                   "poll",
	"prctl":                   "prctl",
	"pread64":                 "fd",
	"preadv":                  "fd",
	"preadv2":                 "fd",
	"prlimit64":               "null",
	"process_madvise":         "fd",
	"process_mrelease":        "fd",
	"process_vm_readv":        "null",
	"process_vm_writev":       "null",
	"pselect6":                "poll",
	"ptrace":                  "ptrace",
	"pwrite64":                "fd",
	"pwritev":                 "fd",
	"pwritev2":                "fd",
	"quotactl":                "pathname",
	"quotactl_fd":             "fd",
	"read":                    "fd",
	"readahead":               "fd",
	"readlink":                "pathname",
	"readlinkat":              "pathname",
	"readv":                   "fd",
	"reboot":                  "null",
	"recvfrom":                "fd",
	"recvmmsg":                "fd",
	"recvmsg":                 "fd",
	"remap_file_pages":        "mem",
	"removexattr":             "pathname",
	"removexattrat":           "pathname",
	"rename":                  "name",
	"renameat":                "name",
	"renameat2":               "name",
	"request_key":             "keyctl",
	"restart_syscall":         "null",
	"rmdir":                   "pathname",
	"rseq":                    "null",
	"rt_sigaction":            "null",
	"rt_sigpending":           "null",
	"rt_sigprocmask":          "null",
	"rt_sigqueueinfo":         "null",
	"rt_sigreturn":            "null",
	"rt_sigsuspend":           "null",
	"rt_sigtimedwait":         "null",
	"rt_tgsigqueueinfo":       "null",
	"sched_get_priority_max":  "null",
	"sched_get_priority_min":  "null",
	"sched_getaffinity":       "null",
	"sched_getattr":           "null",
	"sched_getparam":          "null",
	"sched_getscheduler":      "null",
	"sched_rr_get_interval":   "null",
	"sched_setaffinity":       "null",
	"sched_setattr":           "null",
	"sched_setparam":          "null",
	"sched_setscheduler":      "null",
	"sched_yield":             "null",
	"seccomp":                 "seccomp",
	"select":                  "poll",
	"semctl":                  "sysv-op",
	"semget":                  "sysv-id",
	"semop":                   "sysv-op",
	"semtimedop":              "sysv-op",
	"sendfile64":              "null",
	"sendmmsg":                "fd",
	"sendmsg":                 "fd",
	"sendto":                  "fd",
	"set_mempolicy":           "null",
	"set_mempolicy_home_node": "null",
	"set_robust_list":         "null",
	"set_tid_address":         "null",
	"setdomainname":           "null",
	"setfsgid":                "null",
	"setfsuid":                "null",
	"setgid":                  "null",
	"setgroups":               "null",
	"sethostname":             "null",
	"setitimer":               "null",
	"setns":                   "fd",
	"setpgid":                 "null",
	"setpriority":             "null",
	"setregid":                "null",
	"setresgid":               "null",
	"setresuid":               "null",
	"setreuid":                "null",
	"setrlimit":               "null",
	"setsid":                  "null",
	"setsockopt":              "fd",
	"settimeofday":            "null",
	"setuid":                  "null",
	"setxattr":                "pathname",
	"setxattrat":              "pathname",
	"shmat":                   "sysv-op",
	"shmctl":                  "sysv-op",
	"shmdt":                   "sysv-op",
	"shmget":                  "sysv-id",
	"shutdown":                "fd",
	"sigaltstack":             "null",
	"signalfd":                "eventfd",
	"signalfd4":               "eventfd",
	"socket":                  "socket",
	"socketpair":              "socketpair",
	"splice":                  "null",
	"statfs":                  "pathname",
	"statmount":               "null",
	"statx":                   "pathname",
	"swapoff":                 "pathname",
	"swapon":                  "pathname",
	"symlink":                 "name",
	"symlinkat":               "name",
	"sync":                    "null",
	"sync_file_range":         "fd",
	"syncfs":                  "fd",
	"sysfs":                   "null",
	"sysinfo":                 "null",
	"syslog":                  "null",
	"tee":                     "null",
	"tgkill":                  "null",
	"time":                    "null",
	"timer_create":            "null",
	"timer_delete":            "null",
	"timer_getoverrun":        "null",
	"timer_gettime":           "null",
	"timer_settime":           "null",
	"timerfd_create":          "eventfd",
	"timerfd_gettime":         "null",
	"timerfd_settime":         "null",
	"times":                   "null",
	"tkill":                   "null",
	"truncate":                "pathname",
	"umask":                   "null",
	"umount":                  "pathname",
	"unlink":                  "pathname",
	"unlinkat":                "pathname",
	"unshare":                 "null",
	"uprobe":                  "null",
	"uretprobe":               "null",
	"userfaultfd":             "eventfd",
	"ustat":                   "null",
	"utime":                   "pathname",
	"utimensat":               "pathname",
	"utimes":                  "pathname",
	"vfork":                   "proc",
	"vhangup":                 "null",
	"vmsplice":                "fd",
	"wait4":                   "proc",
	"waitid":                  "proc",
	"write":                   "fd",
	"writev":                  "fd",
}
